export type SocialIconSize = 'big' | 'medium' | 'small'
export interface IconProps {
  color?: string
  width?: number
  height?: number
  simpleIcon?: boolean
}
export type SocialNetwork =
  | 'zoom'
  | 'github'
  | 'discord'
  | 'facebook'
  | 'twitter'
  | 'instagram'
  | 'whatsapp'
  | 'vk'
  | 'linkedin'
  | 'vimeo'
  | 'youtube'
  | 'tumblr'
  | 'skype'
  | 'pinterest'
  | 'behance'
  | 'dribbble'
  | 'google-analytics'
  | 'facebook-pixel'
  | 'reddit'
  | 'messenger'
  | 'snapchat'
  | 'apple'
  | 'telegram'
  | 'google'
  | 'tiktok'
  | 'spotify'
  | 'trustpilot'
  | 'twitch'
  | 'google-meet'
  | 'google-maps'
  | 'gmail'
  | 'soundcloud'
  | 'patreon'
  | 'tinder'
  | 'google-calendar'

export type Shapes = 'square' | 'round' | 'rounded'
